name: fuse_wallet_sdk
description: Fuse Wallet SDK now has a Dart implementation, making it even
  easier to integrate blockchain technology into your mobile apps.
version: 0.3.2
homepage: https://fuse.io/sdk
repository: https://github.com/fuseio/fuse_wallet_sdk

environment:
  sdk: ">=3.0.0 <4.0.0"

dependencies:
  bip32: ^2.0.0
  bip39: ^1.0.6
  centrifuge: ^0.14.0
  compute: ^1.0.2
  data_channel: ^2.0.0+1
  decimal: ^2.3.3
  dio: ^5.4.1
  freezed_annotation: ^2.4.1
  hex: ^0.2.0
  http: ^1.2.1
  json_annotation: ^4.8.1
  synchronized: ^3.1.0+1
  userop: ^0.1.8
  web3dart: ^2.7.2

dev_dependencies:
  build_runner: ^2.4.8
  freezed: ^2.4.7
  json_serializable: ^6.7.1
  lints: ^3.0.0
  test: ^1.25.2
